CREATE TABLE USUARIO(
    USUARIO_ID SERIAL PRIMARY KEY , 
    NOME VARCHAR,
    CPF VARCHAR,
    EMAIL VARCHAR,
    SENHA VARCHAR,
    ENDERECO VARCHAR,
    AVALIACAO DECIMAL,
    PERFIL INTEGER
);

CREATE TABLE MOVEIS(
    MOVEL_ID SERIAL PRIMARY KEY ,
    TIPO VARCHAR
);

CREATE TABLE STATUS(
    STATUS_ID SERIAL PRIMARY KEY ,
    NOME VARCHAR
);

CREATE TABLE VENDA(
    VENDA_ID SERIAL PRIMARY KEY ,
    USUARIO_ID INTEGER,
    MOVEL_ID INTEGER,
    STATUS_ID INTEGER,
    DATA_VENDA TIMESTAMP,
    IMAGEM VARCHAR,
    VALOR, DECIMAL,
    OBSERVACAO VARCHAR,
    USUARIO_COMPRADOR_ID INTEGER
);
CREATE TABLE AVALIACAO(
    USUARIO_ID INTEGER,
    NOTA DECIMAL
);

